exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0  # Use the ref you want to point at
    hooks:
    - id: autopep8-wrapper
    - id: check-merge-conflict
    - id: debug-statements
    - id: requirements-txt-fixer
verbose: true