# Generated by Django 2.1.1 on 2018-09-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='risk_fields',
                to='custom.RiskType'
            ),
            preserve_default=False,
        ),
    ]
