# Generated by Django 2.1.1 on 2018-10-01 17:34

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_riskfield_risk_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskfield',
            options={'ordering': ('id',), 'verbose_name': 'Risk Field', 'verbose_name_plural': 'Risk Fields'},
        ),
        migrations.AlterModelOptions(
            name='risktype',
            options={'ordering': ('-id',), 'verbose_name': 'Risk Type', 'verbose_name_plural': 'Risk Types'},
        ),
        migrations.AddField(
            model_name='risktype',
            name='table_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('date', 'Date'), ('number', 'Number'), ('currency', 'Currency'), ('option', 'Option'), ('color', 'Color'), ('bool', 'Boolean')], default='text', max_length=20),
        ),
    ]
